### ISSUE TITLE
Kubernetes Support

### ISSUE THREAD

**Issue by josiahbryan** [containers/ramalama#273] opened 2024-10-09 19:11 UTC
Crazy thought - since you're running these in docker, any chance I could instead deploy the containers to my kubernetes cluster? I'm quite out of my depth as far as what's going on under the hood here in your project, just connecting thematic concepts.

Of course, I'm absolutely able to just package `ramalama` up in it's own `Dockerfile` and shoot it into my cluster that way - just thinking outside the box. Any feedback is welcome!

Apologies if this is not the right forum for discussion-type things (vs issues) - is there a better place to ask these theoretical-type of questions as well?

**Comment by rhatdan** [comment] 2024-10-09 19:44
Yes it is actually fairly simple to generate a kube.yaml out of the default ramalama serve command.  Just need someone to sit down and write it.  We do this for Quadlets now, which is a mechanism for running containers and pods under systemd via Podman, very similar to what you want to do with Kubernetes.

**Comment by josiahbryan** [comment] 2024-10-09 19:48
@rhatdan interesting! I'd love to see how that's done for Quadlets, but #183 makes sounds like it's still not done (issue still open?) - is there code written that does that already?

**Comment by rhatdan** [comment] 2024-10-14 11:52
Closing as a duplicate of https://github.com/containers/ramalama/issues/183

Still not done, but I played with it a little, Of course if you are interested in opening a PR?

**Closed by rhatdan** 2024-10-14 11:52 UTC
